<?php
/**
 * brace check - checks whether delimiters are symmetric or not
 *
 * @author Fedor Vyrzhykovsky
 */

namespace app\components;
use yii\base\Widget;

class url_converter extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $errStr =  'Error: string is NULL';
        $errorMessage = '[ ' . $errStr . ' ]';
        if ($this->message === null) {
            return $this->message = $errorMessage;
        } else {
            return $nStr = $this->strToUrl($this->message);
        }
    }

    public function russianToTranslit($string){
         $converter = array(
            'а' => 'a',   'б' => 'b',   'в' => 'v',
            'г' => 'g',   'д' => 'd',   'е' => 'e',
            'ё' => 'e',   'ж' => 'zh',  'з' => 'z',
            'и' => 'i',   'й' => 'y',   'к' => 'k',
            'л' => 'l',   'м' => 'm',   'н' => 'n',
            'о' => 'o',   'п' => 'p',   'р' => 'r',
            'с' => 's',   'т' => 't',   'у' => 'u',
            'ф' => 'f',   'х' => 'h',   'ц' => 'c',
            'ч' => 'ch',  'ш' => 'sh',  'щ' => 'sch',
            'ь' => '',    'ы' => 'y',   'ъ' => '',
            'э' => 'e',   'ю' => 'yu',  'я' => 'ya',
            'А' => 'A',   'Б' => 'B',   'В' => 'V',
            'Г' => 'G',   'Д' => 'D',   'Е' => 'E',
            'Ё' => 'E',   'Ж' => 'Zh',  'З' => 'Z',
            'И' => 'I',   'Й' => 'Y',   'К' => 'K',
            'Л' => 'L',   'М' => 'M',   'Н' => 'N',
            'О' => 'O',   'П' => 'P',   'Р' => 'R',
            'С' => 'S',   'Т' => 'T',   'У' => 'U',
            'Ф' => 'F',   'Х' => 'H',   'Ц' => 'C',
            'Ч' => 'Ch',  'Ш' => 'Sh',  'Щ' => 'Sch',
            'Ь' => '',    'Ы' => 'Y',   'Ъ' => '',
            'Э' => 'E',   'Ю' => 'Yu',  'Я' => 'Ya'
        );
        //Converts the specified characters
        return strtr($string, $converter);
    }

    function strToUrl($str) {
        //еще нужно удалять все лишние 0-9
        $str = $this->russianToTranslit($str);
        //make all words
        $str = strtolower($str);
        //replace symbols to '-' in $str
         $str = preg_replace('~[^-a-z0-9_]+~u', '-', $str);
        // delete the start and ending symbols => '-
        $str = trim($str, "-");
        return $str;
    }
}