<?php
/**
 * url_converter
 *
 * @author Fedor Vyrzhykovsky
 */

namespace app\components;
use yii\base\Widget;

class url_converter extends Widget
{
   public $message;
   public $converter = array(
        'а' => 'a',   'б' => 'b',   'в' => 'v',
        'г' => 'g',   'д' => 'd',   'е' => 'e',
        'ё' => 'e',   'ж' => 'zh',  'з' => 'z',
        'и' => 'i',   'й' => 'y',   'к' => 'k',
        'л' => 'l',   'м' => 'm',   'н' => 'n',
        'о' => 'o',   'п' => 'p',   'р' => 'r',
        'с' => 's',   'т' => 't',   'у' => 'u',
        'ф' => 'f',   'х' => 'h',   'ц' => 'c',
        'ч' => 'ch',  'ш' => 'sh',  'щ' => 'sch',
        'ь' => '',    'ы' => 'y',   'ъ' => '',
        'э' => 'e',   'ю' => 'yu',  'я' => 'ya',
        'А' => 'A',   'Б' => 'B',   'В' => 'V',
        'Г' => 'G',   'Д' => 'D',   'Е' => 'E',
        'Ё' => 'E',   'Ж' => 'Zh',  'З' => 'Z',
        'И' => 'I',   'Й' => 'Y',   'К' => 'K',
        'Л' => 'L',   'М' => 'M',   'Н' => 'N',
        'О' => 'O',   'П' => 'P',   'Р' => 'R',
        'С' => 'S',   'Т' => 'T',   'У' => 'U',
        'Ф' => 'F',   'Х' => 'H',   'Ц' => 'C',
        'Ч' => 'Ch',  'Ш' => 'Sh',  'Щ' => 'Sch',
        'Ь' => '',    'Ы' => 'Y',   'Ъ' => '',
        'Э' => 'E',   'Ю' => 'Yu',  'Я' => 'Ya'
    );

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $errStr =  '[ ' .'Error: string is NULL'. ' ]';
        if ($this->message === null) {
            return $this->message = $errStr;
        } else {
            return $nStr = $this->strToUrl($this->message);
        }
    }

    public function russianToTranslit($message){
        //Преобразуем символы так, что при проходе массива он забирал по ключу=>значение
        return strtr($message, $this->converter);
    }

    function strToUrl($message) {
        //преобразуем нашу строку согласно функции russianToTranslit($message)
        $str = $this->russianToTranslit($message);
        //заменяем все заглавные на маленькие
        $str = strtolower($str);
        //замена пробелов на символ '-' согласно регулярному выражению '~[^-a-z0-9_]+~u'
         $str = preg_replace('~[^-a-z0-9_]+~u', '-', $str);
        // в начале и в конце строки убираем лишние символы '-'
        $str = trim($str, "-");
        //возращяем полученный результат
        return $str;
    }
}
